Refactor errors into common function

diff --git a/bin/update b/bin/update
--- a/bin/update
+++ b/bin/update
@@ -5,6 +5,13 @@
 
 umask 0002
 
+# Terminate displaying the specified error message
+error()
+{
+  echo '[Error]' "$@" 1>&2
+  exit 1
+}
+
 if [ $(hostname) = istlab ] ; then
   BASE=/home/dds/web/balab
   rm -rf $BASE/new
@@ -21,8 +28,7 @@ if ! find content -type f |
   sed 's/ *$//' |
   sort -u |
   diff doc/valid_categories - ; then
-    echo 'Invalid content category used; see above'
-    exit 1
+    error 'Invalid content category used; see above'
 fi
 
 chmod 2775 $BASE/new
@@ -32,38 +38,32 @@ pelican content/ --output=$BASE/new
 if test $(stat -c %s $BASE/new/category/members.html) -gt 20000 ; then
   echo "Members: OK"
 else
- echo "[Error] File $BASE/new/category/members.html appears truncated, please check members file and update again!"
-  exit 1
+ error "File $BASE/new/category/members.html appears truncated, please check members file and update again!"
 fi
 
 if test $(stat -c %s $BASE/new/category/software.html) -gt 7000 ; then
   echo "Software: OK"
 else
- echo "[Error] File $BASE/new/category/software.html appears truncated, please check software file and update again!"
-  exit 1
+ error "File $BASE/new/category/software.html appears truncated, please check software file and update again!"
 fi
 
 if test $(stat -c %s $BASE/new/category/projects.html) -gt 10000 ; then
   echo "Projects: OK"
 else
- echo "[Error] File $BASE/new/category/projects.html appears truncated, please check projects file and update again!"
-  exit 1
+ error "File $BASE/new/category/projects.html appears truncated, please check projects file and update again!"
 fi
 
 if test $(stat -c %s $BASE/new/category/alumni.html) -gt 5000 ; then
   echo "Alumni: OK"
 else
- echo "[Error] File $BASE/new/category/alumni.html appears truncated, please check alumni file and update again!"
-  exit 1
+ error "File $BASE/new/category/alumni.html appears truncated, please check alumni file and update again!"
 fi
 
 if test $(stat -c %s $BASE/new/category/yearly-reports.html) -gt 5000 ; then
   echo "Yearly reports: OK"
 else
- echo "[Error] File $BASE/new/category/yearly-reports.html appears truncated, please check yearly-reports file and update again!"
-  exit 1
+ error "File $BASE/new/category/yearly-reports.html appears truncated, please check yearly-reports file and update again!"
 fi
-
 
 test -d $BASE/current && mv $BASE/current $BASE/old
 mv $BASE/new $BASE/current
