Update for istlab

diff --git a/bin/update b/bin/update
--- a/bin/update
+++ b/bin/update
@@ -3,22 +3,27 @@
 # Refresh the site's content
 #
 
-#BASE=/home/dds/web/balab
-BASE=balab
-
 umask 0002
-mkdir $BASE/new
-test $(hostname) == istlab &&  chgrp iweb $BASE/new 
+
+if [ $(hostname) = istlab ] ; then
+  BASE=/home/dds/web/balab
+  mkdir $BASE/new
+  chgrp iweb $BASE/new
+else
+  BASE=balab
+  mkdir $BASE/new
+fi
+
 chmod 2775 $BASE/new
 pelican content/ --output=$BASE/new
 
 #Sanity check
-test $(stat -c %s $BASE/current/category/members.html) -lt 20000 && { echo "[Error] File $BASE/current/category/members.html might be not created, please check members file and update again!"; exit; }
-test $(stat -c %s $BASE/current/category/software.html) -lt 7000 && { echo "[Error] File $BASE/current/category/software.html might be not created, please check software file and update again!"; exit; }
-test $(stat -c %s $BASE/current/category/projects.html) -lt 10000 && { echo "[Error] File $BASE/current/category/projects.html might be not created, please check projects file and update again!"; exit; }
-test $(stat -c %s $BASE/current/category/alumni.html) -lt 5000 && { echo "[Error] File $BASE/current/category/alumni.html might be not created, please check alumni file and update again!"; exit; }
-test $(stat -c %s $BASE/current/category/yearly-reports.html) -lt 5000 && { echo "[Error] File $BASE/current/category/yearly-reports.html might be not created, please check yearly-reports file and update again!"; exit; }
+test $(stat -c %s $BASE/current/category/members.html) -gt 20000 || { echo "[Error] File $BASE/current/category/members.html appears truncated, please check members file and update again!"; exit 1; }
+test $(stat -c %s $BASE/current/category/software.html) -gt 7000 || { echo "[Error] File $BASE/current/category/software.html appears truncated, please check software file and update again!"; exit 1; }
+test $(stat -c %s $BASE/current/category/projects.html) -gt 10000 || { echo "[Error] File $BASE/current/category/projects.html appears truncated, please check projects file and update again!"; exit 1; }
+test $(stat -c %s $BASE/current/category/alumni.html) -gt 5000 || { echo "[Error] File $BASE/current/category/alumni.html appears truncated, please check alumni file and update again!"; exit 1; }
+test $(stat -c %s $BASE/current/category/yearly-reports.html) -gt 5000 || { echo "[Error] File $BASE/current/category/yearly-reports.html appears truncated, please check yearly-reports file and update again!"; exit 1; }
 
-mv $BASE/current $BASE/old
+test -d $BASE/current && mv $BASE/current $BASE/old
 mv $BASE/new $BASE/current
 rm -rf $BASE/old
