Make tests more verbose

diff --git a/bin/update b/bin/update
--- a/bin/update
+++ b/bin/update
@@ -18,11 +18,41 @@ chmod 2775 $BASE/new
 pelican content/ --output=$BASE/new
 
 #Sanity check
-test $(stat -c %s $BASE/new/category/members.html) -gt 20000 || { echo "[Error] File $BASE/new/category/members.html appears truncated, please check members file and update again!"; exit 1; }
-test $(stat -c %s $BASE/new/category/software.html) -gt 7000 || { echo "[Error] File $BASE/new/category/software.html appears truncated, please check software file and update again!"; exit 1; }
-test $(stat -c %s $BASE/new/category/projects.html) -gt 10000 || { echo "[Error] File $BASE/new/category/projects.html appears truncated, please check projects file and update again!"; exit 1; }
-test $(stat -c %s $BASE/new/category/alumni.html) -gt 5000 || { echo "[Error] File $BASE/new/category/alumni.html appears truncated, please check alumni file and update again!"; exit 1; }
-test $(stat -c %s $BASE/new/category/yearly-reports.html) -gt 5000 || { echo "[Error] File $BASE/new/category/yearly-reports.html appears truncated, please check yearly-reports file and update again!"; exit 1; }
+if test $(stat -c %s $BASE/new/category/members.html) -gt 20000 ; then
+  echo "Members: OK"
+else
+ echo "[Error] File $BASE/new/category/members.html appears truncated, please check members file and update again!"
+  exit 1
+fi
+
+if test $(stat -c %s $BASE/new/category/software.html) -gt 7000 ; then
+  echo "Software: OK"
+else
+ echo "[Error] File $BASE/new/category/software.html appears truncated, please check software file and update again!"
+  exit 1
+fi
+
+if test $(stat -c %s $BASE/new/category/projects.html) -gt 10000 ; then
+  echo "Projects: OK"
+else
+ echo "[Error] File $BASE/new/category/projects.html appears truncated, please check projects file and update again!"
+  exit 1
+fi
+
+if test $(stat -c %s $BASE/new/category/alumni.html) -gt 5000 ; then
+  echo "Alumni: OK"
+else
+ echo "[Error] File $BASE/new/category/alumni.html appears truncated, please check alumni file and update again!"
+  exit 1
+fi
+
+if test $(stat -c %s $BASE/new/category/yearly-reports.html) -gt 5000 ; then
+  echo "Yearly reports: OK"
+else
+ echo "[Error] File $BASE/new/category/yearly-reports.html appears truncated, please check yearly-reports file and update again!"
+  exit 1
+fi
+
 
 test -d $BASE/current && mv $BASE/current $BASE/old
 mv $BASE/new $BASE/current
